export const GET_BOOKS_REQUEST = "GET_BOOKS_REQUEST";
export const GET_BOOKS_SUCCESS = "GET_BOOKS_SUCCESS";
export const GET_BOOKS_FAIL = "GET_PRODUCTS_FAIL";
export const RESERVE_BOOK = "RESERVE_BOOK";
