export const GET_RESERVEDBOOKS_REQUEST = "GET_RESERVEDBOOKS_REQUEST";
export const GET_RESERVEDBOOKS_SUCCESS = "GET_RESERVEDBOOKS_SUCCESS";
export const GET_RESERVEDBOOKS_FAIL = "GET_RESERVEDBOOKS_FAIL";
export const RETURN_BOOK = "RETURN_BOOK";
export const RETURN_BOOK_FAIL = "RETURN_BOOK_FAIL";
